### ISSUE TITLE
gwt-window still depends on elemental2 1.0.0

### ISSUE THREAD

**Issue by niloc132** [tbroyer/gwt-window#1]
https://github.com/gwtproject/gwt-window/commit/b3fe53a5dc44ce316fb650ad8fcbfdbff1365068 has not yet been released, so there is no public build that depends on elemental2-dom 1.1.0, which has breaking API changes. This prevents J2CL projects from building cleanly against it.

**Comment by tbroyer** [comment]
Out of memory, we wanted to possibly change the GAV for gwt-event, but that indeed is not blocking another RC.

**Comment by tbroyer** [comment]
v1.0.0-RC3 just released (should reach Central soon)
